#ifndef CONFIGURE_H
#define CONFIGURE_H

#define USE_TATTLETALE
/* #define SUPPRESS_EXIT_ENTRY_IN_TATTLE */

typedef enum {
    ES_NO_EVENT, ES_ERROR,
    ES_INIT, ES_ENTRY, ES_EXIT, ES_KEYINPUT, ES_LISTEVENTS,
    ES_TIMEOUT, ES_TIMERACTIVE, ES_TIMERSTOPPED,

    EV_START_BUTTON,

    EV_TAPE_FRONT_L,
    EV_TAPE_FRONT_LM,
    EV_TAPE_FRONT_M,
    EV_TAPE_FRONT_MR,
    EV_TAPE_FRONT_R,
    EV_TAPE_REAR_L,
    EV_TAPE_REAR_R,
    EV_TAPE_MASK_CHANGED,
    EV_FRONT_WIDE_BLACK,
    EV_FRONT_ALL_BLACK,
    EV_FIELD_MARKER_CROSS,
    EV_TAPE_FRONT_CROSS,
    EV_TAPE_REAR_CROSS,
    EV_TAPE_LOST,
    EV_ISZ_ENTRY,
    EV_ISZ_ENTRY_CANDIDATE,
    EV_ISZ_CONFIRMED,
    EV_BOUNDARY_DETECTED,
    EV_LEFT_EDGE_LOCKED,
    EV_RIGHT_EDGE_LOCKED,
    EV_LEFT_BOUNDARY_DANGER,
    EV_RIGHT_BOUNDARY_DANGER,

    EV_TRACKWIRE_LEFT,
    EV_TRACKWIRE_RIGHT,
    EV_TRACKWIRE_BOTH,

    EV_BUMPER_HIT,
    EV_BUMPER_FRONT,
    EV_BUMPER_LEFT,
    EV_BUMPER_RIGHT,
    EV_BUMPER_REAR,

    EV_BEACON_LOCKED,
    EV_BEACON_LOST,
    EV_BEACON_LEFT_STRONG,
    EV_BEACON_RIGHT_STRONG,
    EV_BEACON_CENTERED,

    EV_FLYWHEEL_READY,
    EV_BALL_SERVER_DONE,
    EV_BALL_FIRED,
    EV_MAG_EMPTY,

    EV_TIMER_EXPIRED,
    EV_RECOVERY_DONE,
    EV_NAV_FAILED,
    EV_TAPE_PANIC,
    EV_LOW_BATTERY,
    EV_FAULT,

    NUMBEROFEVENTS,
} ES_EventTyp_t;

static const char *EventNames[] = {
    "ES_NO_EVENT", "ES_ERROR", "ES_INIT", "ES_ENTRY", "ES_EXIT",
    "ES_KEYINPUT", "ES_LISTEVENTS", "ES_TIMEOUT", "ES_TIMERACTIVE",
    "ES_TIMERSTOPPED",
    "EV_START_BUTTON",
    "EV_TAPE_FRONT_L", "EV_TAPE_FRONT_LM", "EV_TAPE_FRONT_M",
    "EV_TAPE_FRONT_MR", "EV_TAPE_FRONT_R", "EV_TAPE_REAR_L",
    "EV_TAPE_REAR_R", "EV_TAPE_MASK_CHANGED", "EV_FRONT_WIDE_BLACK",
    "EV_FRONT_ALL_BLACK", "EV_FIELD_MARKER_CROSS",
    "EV_TAPE_FRONT_CROSS", "EV_TAPE_REAR_CROSS",
    "EV_TAPE_LOST", "EV_ISZ_ENTRY", "EV_ISZ_ENTRY_CANDIDATE",
    "EV_ISZ_CONFIRMED", "EV_BOUNDARY_DETECTED",
    "EV_LEFT_EDGE_LOCKED", "EV_RIGHT_EDGE_LOCKED",
    "EV_LEFT_BOUNDARY_DANGER", "EV_RIGHT_BOUNDARY_DANGER",
    "EV_TRACKWIRE_LEFT", "EV_TRACKWIRE_RIGHT", "EV_TRACKWIRE_BOTH",
    "EV_BUMPER_HIT", "EV_BUMPER_FRONT", "EV_BUMPER_LEFT", "EV_BUMPER_RIGHT",
    "EV_BUMPER_REAR",
    "EV_BEACON_LOCKED", "EV_BEACON_LOST", "EV_BEACON_LEFT_STRONG",
    "EV_BEACON_RIGHT_STRONG", "EV_BEACON_CENTERED",
    "EV_FLYWHEEL_READY", "EV_BALL_SERVER_DONE", "EV_BALL_FIRED",
    "EV_MAG_EMPTY",
    "EV_TIMER_EXPIRED", "EV_RECOVERY_DONE", "EV_NAV_FAILED",
    "EV_TAPE_PANIC", "EV_LOW_BATTERY", "EV_FAULT",
    "NUMBEROFEVENTS",
};

#define EVENT_CHECK_HEADER "ProjectEventChecker.h"
#define EVENT_CHECK_LIST   CheckProjectEvents

#define TIMER_UNUSED ((pPostFunc)0)

#define TAPE_TIMER          0
#define TRACKWIRE_TIMER     1
#define BUMPER_TIMER        2
#define BEACON_TIMER        3
#define FLYWHEEL_TIMER      4
#define BALL_SERVER_TIMER   5
#define RECOVERY_TIMER      6
#define BATTERY_TIMER       7
#define NAV_PRIMARY_TIMER   8
#define NAV_SECONDARY_TIMER 9
#define NAV_TOTAL_GUARD_TIMER 10

#define NAV_TIMER           NAV_PRIMARY_TIMER
#define NAV_GUARD_TIMER     NAV_SECONDARY_TIMER
#define NAV_PATTERN_CHECK_TIMER NAV_SECONDARY_TIMER
#define NAV_BEACON_SCAN_TIMER NAV_PRIMARY_TIMER
#define NAV_EXIT_START_TIMER  NAV_PRIMARY_TIMER
#define NAV_EDGE_SEEK_TIMER   NAV_PRIMARY_TIMER
#define NAV_BACK_SEARCH_TIMER NAV_PRIMARY_TIMER
#define NAV_REAR_CAPTURE_TIMER NAV_PRIMARY_TIMER
#define NAV_EDGE_APPROACH_TIMER NAV_PRIMARY_TIMER
#define NAV_CORNER_EXIT_TIMER NAV_PRIMARY_TIMER
#define REC_BACKUP_TIMER      NAV_PRIMARY_TIMER
#define REC_STRAFE_11IN_TIMER NAV_PRIMARY_TIMER
#define REC_RECENTER_TIMER    NAV_PRIMARY_TIMER
#define LEFT_REACQUIRE_TIMER  NAV_PRIMARY_TIMER
#define RIGHT_EDGE_ACQUIRE_TIMER NAV_PRIMARY_TIMER
#define FISHBONE_ACQUIRE_TIMER NAV_PRIMARY_TIMER
#define FISHBONE_FOLLOW_TIMER  NAV_PRIMARY_TIMER
#define POST_FISHBONE_ISZ_TIMER NAV_PRIMARY_TIMER
#define FINAL_LEFT_EDGE_ACQUIRE_TIMER NAV_PRIMARY_TIMER
#define CROSS_TO_RIGHT_MAX_TIMER NAV_PRIMARY_TIMER
#define NAV_ISZ_CREEP_TIMER   NAV_PRIMARY_TIMER
#define ISZ_CENTER_SETTLE_TIMER NAV_PRIMARY_TIMER
#define NAV_ISZ_SEARCH_TIMER  NAV_PRIMARY_TIMER
#define CROSS_TO_RIGHT_SUPPRESS_TIMER NAV_SECONDARY_TIMER
#define ISZ_EXTRA_CREEP_TIMER NAV_SECONDARY_TIMER

#define TIMER0_RESP_FUNC    PostTapeService
#define TIMER1_RESP_FUNC    PostTrackWireService
#define TIMER2_RESP_FUNC    PostBumperService
#define TIMER3_RESP_FUNC    PostBeaconService
#define TIMER4_RESP_FUNC    PostLauncherService
#define TIMER5_RESP_FUNC    PostLauncherService
#define TIMER6_RESP_FUNC    PostTopHSM
#define TIMER7_RESP_FUNC    PostBatteryService
#define TIMER8_RESP_FUNC    PostTopHSM
#define TIMER9_RESP_FUNC    PostTopHSM
#define TIMER10_RESP_FUNC   PostTopHSM
#define TIMER11_RESP_FUNC   TIMER_UNUSED
#define TIMER12_RESP_FUNC   TIMER_UNUSED
#define TIMER13_RESP_FUNC   TIMER_UNUSED
#define TIMER14_RESP_FUNC   TIMER_UNUSED
#define TIMER15_RESP_FUNC   TIMER_UNUSED

#define MAX_NUM_SERVICES 8
#define NUM_SERVICES 8

#define SERV_0_HEADER "TopHSM.h"
#define SERV_0_INIT InitTopHSM
#define SERV_0_RUN RunTopHSM
#define SERV_0_QUEUE_SIZE 12

#if NUM_SERVICES > 1
#define SERV_1_HEADER "DriveService.h"
#define SERV_1_INIT InitDriveService
#define SERV_1_RUN RunDriveService
#define SERV_1_QUEUE_SIZE 4
#endif

#if NUM_SERVICES > 2
#define SERV_2_HEADER "TapeService.h"
#define SERV_2_INIT InitTapeService
#define SERV_2_RUN RunTapeService
#define SERV_2_QUEUE_SIZE 8
#endif

#if NUM_SERVICES > 3
#define SERV_3_HEADER "TrackWireService.h"
#define SERV_3_INIT InitTrackWireService
#define SERV_3_RUN RunTrackWireService
#define SERV_3_QUEUE_SIZE 6
#endif

#if NUM_SERVICES > 4
#define SERV_4_HEADER "BumperService.h"
#define SERV_4_INIT InitBumperService
#define SERV_4_RUN RunBumperService
#define SERV_4_QUEUE_SIZE 6
#endif

#if NUM_SERVICES > 5
#define SERV_5_HEADER "BeaconService.h"
#define SERV_5_INIT InitBeaconService
#define SERV_5_RUN RunBeaconService
#define SERV_5_QUEUE_SIZE 8
#endif

#if NUM_SERVICES > 6
#define SERV_6_HEADER "LauncherService.h"
#define SERV_6_INIT InitLauncherService
#define SERV_6_RUN RunLauncherService
#define SERV_6_QUEUE_SIZE 8
#endif

#if NUM_SERVICES > 7
#define SERV_7_HEADER "BatteryService.h"
#define SERV_7_INIT InitBatteryService
#define SERV_7_RUN RunBatteryService
#define SERV_7_QUEUE_SIZE 4
#endif

#define POST_KEY_FUNC ES_PostAll
#define NUM_DIST_LISTS 0

#endif
