#ifndef PROJECT_EVENTS_H
#define PROJECT_EVENTS_H

/* This is the design event table from Design 1. */
typedef enum {
    EV_START_BUTTON = 1,

    EV_TAPE_FRONT_L,
    EV_TAPE_FRONT_LM,
    EV_TAPE_FRONT_M,
    EV_TAPE_FRONT_MR,
    EV_TAPE_FRONT_R,
    EV_TAPE_REAR_L,
    EV_TAPE_REAR_R,
    EV_TAPE_MASK_CHANGED,
    EV_FRONT_WIDE_BLACK,
    EV_FRONT_ALL_BLACK,
    EV_FIELD_MARKER_CROSS,
    EV_TAPE_FRONT_CROSS,
    EV_TAPE_REAR_CROSS,
    EV_TAPE_LOST,
    EV_ISZ_ENTRY,
    EV_ISZ_ENTRY_CANDIDATE,
    EV_ISZ_CONFIRMED,
    EV_BOUNDARY_DETECTED,
    EV_LEFT_EDGE_LOCKED,
    EV_RIGHT_EDGE_LOCKED,
    EV_LEFT_BOUNDARY_DANGER,
    EV_RIGHT_BOUNDARY_DANGER,

    EV_TRACKWIRE_LEFT,
    EV_TRACKWIRE_RIGHT,
    EV_TRACKWIRE_BOTH,

    EV_BUMPER_HIT,
    EV_BUMPER_FRONT,
    EV_BUMPER_LEFT,
    EV_BUMPER_RIGHT,
    EV_BUMPER_REAR,

    EV_BEACON_LOCKED,
    EV_BEACON_LOST,
    EV_BEACON_LEFT_STRONG,
    EV_BEACON_RIGHT_STRONG,
    EV_BEACON_CENTERED,

    EV_FLYWHEEL_READY,
    EV_BALL_SERVER_DONE,
    EV_BALL_FIRED,
    EV_MAG_EMPTY,

    EV_TIMER_EXPIRED,
    EV_RECOVERY_DONE,
    EV_NAV_FAILED,
    EV_TAPE_PANIC,
    EV_LOW_BATTERY,
    EV_FAULT
} ProjectEventType_t;

#endif
